apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts-db.first-project-production.192-168-64-2.nip.io
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.first-project-production.svc.cluster.local
